#!/bin/sh

pkgs="$(pacman -Qtdq 2>/dev/null)"
[ -z "$pkgs" ] && exit 0

echo "Orphan packages that were installed as a dependency and are no longer required by any package:"
echo "$pkgs" | while IFS= read -r pkg; do
  pacman -Qi "$pkg" | awk -F: '/^Description/ {print "\t'"$pkg"': "$2}'
done

echo "You can mark them as explicitly installed with 'pacman -D --asexplicit <pkg>'"
