alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lha --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias p='sudo pacman -Syu'
alias ga='git ls-files -mo | fzf -m | xargs -r git add; git status'
alias gr='git diff --cached --name-only | fzf -m | xargs -r git rest HEAD; git status'
alias gs='git status'
alias notes='vim ~/Documents/notes.txt'
alias vcfg=$'vim $(du -a ~/.config/* | awk \'{print $2}\' | fzf)'
alias vsc=$'vim $(du -a ~/.scripts/ | awk \'{print $2}\' | fzf)'

