#!/usr/bin/env bash

# checkout branch
git_checkout_branch() {
  git checkout "$(git branch -r | sed "s/ origin\///" | fzf)"
  git status
}

# Quick commit with message without quotes
git_quick_commit() {
  message=$*
  if [[ $message ]]; then
    git commit -m "${message}"
  else
    printf "\\033[31mERROR:\\033[0m Commit message required\\n"
    return 1
  fi
}

dotfiles_git_quick_commit() {
  message=$*
  if [[ $message ]]; then
    git --git-dir="$DOTFILES_DIR" --work-tree="$HOME" commit -m "${message}"
  else
    printf "\\033[31mERROR:\\033[0m Commit message required\\n"
    return 1
  fi
}

# edit config
ec() {
  file=$(rg --files --hidden --no-ignore "$XDG_CONFIG_HOME" | fzf)
  [ -z "$file" ] && return
  $EDITOR "$file"
}

# edit script
es() {
  file=$(rg --files "$SCRIPTS_DIR" | fzf)
  [ -z "$file" ] && return
  $EDITOR "$file"
}

# edit vimrc
ev() {
  $EDITOR "$XDG_CONFIG_HOME/nvim/init.lua"
}

#edit notes
en() {
  $EDITOR "$DOCUMENTS_DIR/notes.txt"
}

#edit todo
et() {
  $EDITOR "$DOCUMENTS_DIR/todo.txt"
}

# check weather
weather() {
  curl wttr.in/"$(readlink /etc/localtime | cut -d "/" -f6)"
}

# check command
cheat() {
  curl cheat.sh/"$1"
}

# termbin
termbin() {
  nc termbin.com 9999 | tee /dev/tty | xclip -selection clipboard
}

# fzf process kill
fkill() {
  command ps aux | sed 1d | fzf -m | awk '{print $2}' | xargs -r -t sudo kill -"${1:-9}"
}

# pip install and add package to list
pipinstall() {
  [ -z "$@" ] && return
  pip install "$@" && pip freeze --user > "$XDG_CONFIG_HOME/packages/pkglist-python.txt"
}

# pip uninstall and add package to list
pipremove() {
  [ -z "$@" ] && return
  pip uninstall "$@" && pip freeze --user > "$XDG_CONFIG_HOME/packages/pkglist-python.txt"
}

# Make a directory and immediately cd to it
mkcd() {
  mkdir -p -v "$@" && cd "$@" || return
}

# Check the spelling of a word (no output = correct)
spell() {
  echo "$@" | aspell pipe | grep -v 'but really Aspell' | awk -F ':' '{print $2}'
}

# Format xml from system clipboard and copy it
xmlformat() {
  xclip -o -selection clipboard | xmllint --format - | xclip -i -selection clipboard
}

# Colored tail wrapper
colored_tail() {
  command tail "$@" | ccze -A -o nolookups
}

# Colored ps wrapper
colored_ps() {
  command ps "$@" | ccze -A -o nolookups | less
}

qrcode () {
  input="$*"
  [ -z "$input" ] && input="@/dev/stdin"

  curl -d "$input" https://qrcode.show
}
