#!/usr/bin/env bash

# Configure prompt showing vi mode
_set_vi_mode_prompt_strings () {
  NORMAL_MODE_PROMPT="\[\e[33m\][\[\e[m\]\[\e[32m\]\$(__prompt_string_compact_pwd)\[\e[m\]\[\e[33m\]]\[\e[m\] \[\e[33m\]\$(__prompt_string_git_branch)\[\e[m\]\[\e[32m\]N\[\e[m\] \[\e[32m\]:\[\e[m\]\[\e[32m\]:\[\e[m\]\[\e[32m\]:\[\e[m\]"
  INSERT_MODE_PROMPT="\[\e[33m\][\[\e[m\]\[\e[32m\]\$(__prompt_string_compact_pwd)\[\e[m\]\[\e[33m\]]\[\e[m\] \[\e[33m\]\$(__prompt_string_git_branch)\[\e[m\]\[\e[34m\]I\[\e[m\] \[\e[34m\]>\[\e[m\]\[\e[34m\]>\[\e[m\]\[\e[34m\]>\[\e[m\]"
  bind "set vi-cmd-mode-string \"${NORMAL_MODE_PROMPT@P}\""
  bind "set vi-ins-mode-string \"${INSERT_MODE_PROMPT@P}\""
}

# Compact current working directory
__prompt_string_compact_pwd(){
  w='\w'; IFS=/ read -ra a <<< "${w@P}"
  ((c=${#a[@]}-1))
  for e in "${a[@]::$c}"; do
    [[ $e =~ ^\. ]]&&l=2||l=1
    printf '%s/' "${e:0:$l}"
  done;
  echo "${a[$c]}"
}

# Show git branch
__prompt_string_git_branch() {
  current_branch=$(git symbolic-ref HEAD --short 2>/dev/null)
  [ -z "$current_branch" ] && return || echo "$current_branch  "
}
