#!/bin/sh

wal -R &
set-wallpaper &
# xrdb $XDG_CONFIG_HOME/x11/xresources &
compton -b &
dunst &
libinput-gestures-setup start &
setxkbmap us,bg -variant ,phonetic -option 'grp:lalt_lshift_toggle'
xset r rate 300 40
redshift -PO 3200
eval $(ssh-agent)
xbanish -m se &

# exec i3
exec awesome
