#!/bin/sh

wal -R &
set-wallpaper &
# xrdb $XDG_CONFIG_HOME/x11/xresources &
compton -b &
dunst &
libinput-gestures-setup start &
setxkbmap us,bg -variant ,phonetic -option 'grp:lalt_lshift_toggle'
xset r rate 400 40
redshift -PO 3500
eval $(ssh-agent)

exec i3
