#!/bin/sh

monitor-toggle &
wal -R &
set-wallpaper &
# xrdb $XDG_CONFIG_HOME/x11/xresources &
compton -b &
dunst &
libinput-gestures-setup start &
setxkbmap us,bg -variant ,phonetic -option 'grp:win_space_toggle'
xset r rate 300 60
keyd-application-mapper -d
redshift -PO 2500
eval $(ssh-agent) &
xbanish -m se &

exec awesome
