#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# unbind special characters (C-q, C-s etc.)
# (for some reason these should be here, before sourcing the other files)
stty quit    undef
stty erase   undef
stty kill    undef
stty start   undef
stty stop    undef
stty rprnt   undef
stty werase  undef
stty discard undef

# shellcheck disable=SC1090
# Source the remaining config files
while read -r f; do
  source "$f"
done <<< "$(find "$XDG_CONFIG_HOME/bash" -type f,l -not -name bashrc)"
