#!/usr/bin/env bash

# shellcheck disable=SC2155

_green() {
  printf "\1\e[32;1m\2%s\1\e[0m\2" "$1"
}

_yellow() {
  printf "\1\e[33;1m\2%s\1\e[0m\2" "$1"
}

_blue() {
  printf "\1\e[34;1m\2%s\1\e[0m\2" "$1"
}

_magenta() {
  printf "\1\e[35;1m\2%s\1\e[0m\2" "$1"
}

__prompt_string_compact_pwd(){
  local w=$PWD  # Use $PWD to get the current working directory

  # Replace the home directory path with '~'
  if [[ $w == $HOME* ]]; then
    w="~${w#$HOME}"
  fi

  IFS=/ read -ra a <<< "$w"  # Split $w into an array by "/"
  ((c=${#a[@]}-1))  # Get the index of the last element in the array

  # Iterate over all elements except the last one
  for e in "${a[@]::$c}"; do
    # If the directory starts with a dot, show the first two characters
    [[ $e =~ ^\. ]] && l=2 || l=1
    printf '%s/' "${e:0:$l}"
  done

  # Echo the last element of the path (final directory)
  echo "${a[$c]}"
}

__prompt_string_git_branch() {
  local current_branch=$(git symbolic-ref HEAD --short 2>/dev/null)
  [ -z "$current_branch" ] && return || echo "$current_branch  "
}

__prompt_kubernetes_context() {
  local context=$(cat "$XDG_CACHE_HOME/kube-context.txt")
  [ -z "$context" ] && return || echo "$context ⎈"
}

__prompt_mgrafbash() {
  [ -n "$MGRAFBASH" ] && echo "MGRAF:"
}

_prompt_command() {
  history -a 2>/dev/null

  local o_bracket=$(_yellow "[")
  local mgrafbash=$(_magenta "$(__prompt_mgrafbash)")
  local compact_pwd=$(_green "$(__prompt_string_compact_pwd)")
  local c_bracket=$(_yellow "]")
  local branch=$(_yellow "$(__prompt_string_git_branch)")


  local prompt="${o_bracket}${mgrafbash}${compact_pwd}${c_bracket} ${branch}"

  echo -e "$prompt"
}

# vi mode prompts
bind "set vi-cmd-mode-string $(_green "::")"
bind "set vi-ins-mode-string $(_blue ">>")"

PROMPT_COMMAND="_prompt_command"

# These are appended to PROMPT_COMMAND and need at least one char
PS1=" "
PS2="   "
