#!/bin/sh
wal -R &
. ~/.fehbg &
compton -b &
dunst &
poly-launch &
libinput-gestures-setup start &
setxkbmap us,bg -variant ,phonetic -option 'grp:lalt_lshift_toggle'
xset r rate 400 40
redshift -PO 3500
eval $(ssh-agent)

exec i3
