[firefox]
control.h = left
control.j = down
control.k = up
control.l = right

[librewolf]
control.h = left
control.j = down
control.k = up
control.l = right

[brave-browser]
control.h = left
control.j = down
control.k = up
control.l = right

# burp/zaproxy
# 'KEYD_DEBUG=1 keyd-application-mapper -d -v' reports it as 'Active window: focusproxy|focusproxy"
[focusproxy]
control.h = left
control.j = down
control.k = up
control.l = right
control.enter = C-space

[sioyek]
control.j = down
control.k = up

[kitty]
meta.s = M-A-s
meta.v = M-A-v
meta.q = M-A-q
meta.f = M-A-f

meta.h = M-A-h
meta.j = M-A-j
meta.k = M-A-k
meta.l = M-A-l

meta.shift = layer(kitty_move_window)
meta.control = layer(kitty_resize_window)
