#!/bin/sh

CORRECT_USAGE="Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz> <directory>"
FILE_NOT_EXISTS="'$1' - file does not exist"
DIR_NOT_EXISTS="'$2' - directory does not exist"
UNKNOWN_METHOD="extract: '$1' - unknown archive method"

[ -z "$@" ] && echo $CORRECT_USAGE && exit
[ ! -f "$1" ] && echo $FILE_NOT_EXISTS && exit
[ ! -d "$2" ] && echo $DIR_NOT_EXISTS && exit

case $1 in
          *.tar.bz2)	tar xvjf "$1" $2    	 	 ;;
          *.tar.gz)    	tar xvzf "$1" $2    	 	 ;;
          *.tar.xz)    	tar xvJf "$1" $2    	 	 ;;
          *.tar)       	tar xvf "$1" $2     	 	 ;;
          *.tbz2)      	tar xvjf "$1" $2    	 	 ;;
          *.tgz)       	tar xvzf "$1" $2    	 	 ;;
	  *.lzma)      	unlzma "$1" $2      	 	 ;;
          *.bz2)       	bunzip2 "$1" $2	 		 ;;
          *.rar)       	unrar x "$1" -ad $2 	 	 ;;
          *.gz)       	gunzip "$1" $2      	 	 ;;   
          *.zip)       	unzip "$1" -d $2       		 ;;
          *.Z)         	uncompress "$1" $2  	 	 ;;
          *.7z)        	7z x "$1" $2       	 	 ;;
          *.xz)        	unxz "$1" $2			 ;;
          *)           	echo $UNKNOWN_METHOD 		 ;;
esac
