#!/bin/sh

xColor2=$(xrdb -query | grep '\*color2' | awk '{print $NF}')
xColor7=$(xrdb -query | grep '\*color7' | awk '{print $NF}')

SEARCH_TERM=$(cat /dev/null | dmenu -p "Search for:" -nb "$xColor2" -nf "$xColor7" -sb "$xColor7" -sf "$xColor2")

[ -z "$SEARCH_TERM" ] && exit

SONG_ID=$(mpsyt /"$SEARCH_TERM", exit | grep ":" | dmenu -l 10 -nb "$xColor2" -nf "$xColor7" -sb "$xColor7" -sf "$xColor2" | awk '{print $(NF - 1)}')

[ -n "$SONG_ID" ] && mpv "https://youtube.com/watch?v=$SONG_ID"
