#!/bin/sh

LEVEL=3

if [ -n "$1" ]; then
       	LEVEL=$1
fi

for BOOT in $(seq -4 0); do
	printf "############## LOG %s ##############\n" "$BOOT"
	journalctl -p "$LEVEL" -x -b "$BOOT" | cut -d ' ' -f 1-2,5- | sort | uniq -u
	printf "\n\n"
done
