#!/bin/bash
# $1 - full path to the image
# $2 - image width
# $3 - image height
# $4 - scaler type

source "$(ueberzug library)"

ImageLayer 0< <(
    ImageLayer::add [identifier]="image" [x]="0" [y]="0" [path]="$1" [width]="$2" [height]="$3" [scaler]="$4"
    sleep 5
    ImageLayer::remove [identifier]="image"
)
