require('lua.my.plugins')
require('lua.my.plugins-config')
require('lua.my.functions')
require('lua.my.commands')
require('lua.my.autocmds')
require('lua.my.mappings')
require('lua.my.settings')
require('lua.my.theme')

-- require('lua.my.dap')
