pcall(require, "luarocks.loader")
require("awful.autofocus")
require("awful.hotkeys_popup.keys")
require('myawesome.error_handling')
require('myawesome.variables')
require('myawesome.menu')
require('myawesome.wibar')
require('myawesome.mouse_bindings')
require('myawesome.key_bindings')
require('myawesome.rules')
require('myawesome.signals')
